{
 "title": "reth",
 "description": "The reth grafana dashboard\r\n\r\nhttps://github.com/paradigmxyz/reth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(reth_info)" } },
   {
    "name": "blockchain_tree_action",
    "label": "Blockchain Tree Canonicalization Action",
    "query": {
     "query": "label_values(reth_blockchain_tree_make_canonical_duration{instance=\"$instance\"},action)"
    }
   },
   {
    "name": "database_action",
    "label": "Database Storage Providers Action",
    "query": {
     "query": "label_values(reth_storage_providers_database_duration{instance=\"$instance\"},action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage checkpoints",
   "type": "bargauge",
   "description": "The checkpoints mark the last block a stage can recover from in the case of a crash or shutdown of the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_sync_entities_processed{instance=~\"$instance\"} / reth_sync_entities_total{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress as highest block number reached)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "instance" },
  {
   "title": "Average commit time",
   "type": "timeseries",
   "description": "The average commit time for database transactions. Generally, this should not be a limiting factor in syncing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(reth_database_transaction_close_duration_seconds_sum{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) / rate(reth_database_transaction_close_duration_seconds_count{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) >= 0)",
     "legendFormat": "Commit time"
    }
   ]
  },
  {
   "title": "Commit time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_database_transaction_close_duration_seconds{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Average transaction open time",
   "type": "timeseries",
   "description": "The average time a database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(reth_database_transaction_open_duration_seconds_sum{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval]) / rate(reth_database_transaction_open_duration_seconds_count{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Max transaction open time",
   "type": "timeseries",
   "description": "The maximum time the database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_transaction_open_duration_seconds{instance=~\"$instance\", outcome!=\"\", quantile=\"1\"}[$__interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Number of open transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_database_transaction_open_total{instance=~\"$instance\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Max insertion operation time",
   "type": "timeseries",
   "description": "The maximum time the database transaction operation which inserts a large value took.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_operation_large_value_duration_seconds{instance=~\"$instance\", quantile=\"1\"}[$__interval]) > 0) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database tables",
   "type": "piechart",
   "description": "The size of tables in the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_db_table_size{instance=~\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "description": "The size of the database over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_db_table_size{instance=~\"$instance\"} )",
     "legendFormat": "Size ({{job}})"
    }
   ]
  },
  {
   "title": "Database pages",
   "type": "piechart",
   "description": "The type of the pages in the database:\n\n- **Leaf** pages contain KV pairs.\n- **Branch** pages contain information about keys in the leaf pages\n- **Overflow** pages store large values and should generally be avoided if possible",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) ( reth_db_table_pages{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overflow pages by table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sort_desc(reth_db_table_pages{instance=~\"$instance\", type=\"overflow\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Freelist",
   "type": "timeseries",
   "description": "The number of pages on the MDBX freelist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_db_freelist{instance=~\"$instance\"}) by (job)",
     "legendFormat": "Pages ({{job}})"
    }
   ]
  },
  {
   "title": "Database duration per action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_storage_providers_database_duration{instance=~\"$instance\", action=\"$database_action\", quantile=\"0.5\"}",
     "legendFormat": "{{quantile}} percentile"
    },
    {
     "expr": "reth_storage_providers_database_duration{instance=~\"$instance\", action=\"$database_action\", quantile=\"0.95\"} ",
     "legendFormat": "{{quantile}} percentile"
    },
    {
     "expr": "reth_storage_providers_database_duration{instance=~\"$instance\", action=\"$database_action\", quantile=\"1\"} ",
     "legendFormat": "{{quantile}} percentile"
    }
   ]
  },
  { "title": "Static Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Segments size",
   "type": "piechart",
   "description": "The size of segments in the static files",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_static_files_segment_size{instance=~\"$instance\"}",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  {
   "title": "Entries per segment",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "reth_static_files_segment_entries{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files per segment",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "reth_static_files_segment_files{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Static Files growth",
   "type": "timeseries",
   "description": "The size of the static files over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_static_files_segment_size{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max writer commit time",
   "type": "timeseries",
   "description": "The maximum time the static files operation which commits a writer took.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_static_files_jar_provider_write_duration_seconds{instance=~\"$instance\", operation=\"commit-writer\", quantile=\"1\"}[$__interval]) > 0) by (segment)",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  { "title": "Stage: Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }, "repeat": "instance" },
  {
   "title": "Gas processed",
   "type": "timeseries",
   "description": "The amount of gas processed by the execution stage in millions per second.\n\nNote: For mainnet, the block range 2,383,397-2,620,384 will be slow because of the 2016 DoS attack.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Mgas/s" } },
   "targets": [
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "Gas/s (30s)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Gas/s (1m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Gas/s (5m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[10m])",
     "legendFormat": "Gas/s (10m)"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }, "repeat": "instance" },
  {
   "title": "Discovery: Tracked peers",
   "type": "timeseries",
   "description": "The number of tracked peers in the discovery modules (dnsdisc and discv4)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "reth_network_tracked_peers{instance=~\"$instance\"}",
     "legendFormat": "Tracked peers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of incoming and outgoing connections, as well as the number of peers we are currently connected to. Outgoing and incoming connections also count peers we are trying to connect to.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "targets": [
    {
     "expr": "reth_network_outgoing_connections{instance=~\"$instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "reth_network_incoming_connections{instance=~\"$instance\"}",
     "legendFormat": "Incoming connections"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  {
   "title": "P2P errors",
   "type": "timeseries",
   "description": "Internal errors in the P2P module. These are expected to happen from time to time. High error rates should not cause alarm if the node is peering otherwise.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_p2pstream_disconnected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "P2P stream disconnected"
    },
    {
     "expr": "rate(reth_network_pending_session_failures{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed pending sessions"
    },
    {
     "expr": "rate(reth_network_invalid_messages_received{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid messages"
    }
   ]
  },
  {
   "title": "Peer disconnect reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_useless_peer{instance=~\"$instance\"}",
     "legendFormat": "UselessPeer"
    },
    {
     "expr": "reth_network_subprotocol_specific{instance=~\"$instance\"}",
     "legendFormat": "SubprotocolSpecific"
    },
    {
     "expr": "reth_network_already_connected{instance=~\"$instance\"}",
     "legendFormat": "AlreadyConnected"
    },
    {
     "expr": "reth_network_client_quitting{instance=~\"$instance\"}",
     "legendFormat": "ClientQuitting"
    },
    {
     "expr": "reth_network_unexpected_identity{instance=~\"$instance\"}",
     "legendFormat": "UnexpectedHandshakeIdentity"
    },
    {
     "expr": "reth_network_disconnect_requested{instance=~\"$instance\"}",
     "legendFormat": "DisconnectRequested"
    },
    {
     "expr": "reth_network_null_node_identity{instance=~\"$instance\"}",
     "legendFormat": "NullNodeIdentity"
    },
    {
     "expr": "reth_network_tcp_subsystem_error{instance=~\"$instance\"}",
     "legendFormat": "TCPSubsystemError"
    },
    {
     "expr": "reth_network_incompatible{instance=~\"$instance\"}",
     "legendFormat": "IncompatibleP2PVersion"
    },
    {
     "expr": "reth_network_protocol_breach{instance=~\"$instance\"}",
     "legendFormat": "ProtocolBreach"
    },
    {
     "expr": "reth_network_too_many_peers{instance=~\"$instance\"}",
     "legendFormat": "TooManyPeers"
    }
   ]
  },
  {
   "title": "Total Dial Success",
   "type": "timeseries",
   "description": "Number of dials that resulted in a peer being added to the peerset",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 104 },
   "targets": [
    {
     "expr": "reth_network_total_dial_successes{instance=~\"$instance\"}",
     "legendFormat": "Total Dial Successes"
    }
   ]
  },
  { "title": "Downloader: Headers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_headers_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the header downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_headers_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_headers_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_headers_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for headers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  { "title": "Downloader: Bodies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "description": "The internal state of the headers downloader: the number of downloaded headers, and the number of headers sent to the header stage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_responses{instance=~\"$instance\"}",
     "legendFormat": "Buffered responses"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    },
    {
     "expr": "reth_downloaders_bodies_queued_blocks{instance=~\"$instance\"}",
     "legendFormat": "Queued blocks"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the bodies downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_bodies_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_bodies_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_bodies_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for bodies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  {
   "title": "Downloader buffer",
   "type": "timeseries",
   "description": "The number of blocks and size in bytes of those blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_buffered_blocks_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks size "
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Block body response sizes",
   "type": "timeseries",
   "description": "The number of blocks in a request and size in bytes of those block responses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Response size"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_length{instance=~\"$instance\"}",
     "legendFormat": "Individual response length (number of bodies in response)"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes / reth_downloaders_bodies_response_response_length{instance=~\"$instance\"}",
     "legendFormat": "Mean body size in response"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 }, "repeat": "instance" },
  {
   "title": "TxPool Maintenance",
   "type": "timeseries",
   "description": "Transaction pool maintenance metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "reth_transaction_pool_dirty_accounts{instance=~\"$instance\"}",
     "legendFormat": "Dirty Accounts"
    },
    {
     "expr": "reth_transaction_pool_drift_count{instance=~\"$instance\"}",
     "legendFormat": "Drift Count"
    },
    {
     "expr": "reth_transaction_pool_reinserted_transactions{instance=~\"$instance\"}",
     "legendFormat": "Reinserted Transactions"
    },
    {
     "expr": "reth_transaction_pool_deleted_tracked_finalized_blobs{instance=~\"$instance\"}",
     "legendFormat": "Deleted Tracked Finalized Blobs"
    }
   ]
  },
  {
   "title": "Subpool transaction count",
   "type": "timeseries",
   "description": "Tracks the number of transactions in the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool transactions"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Pending pool transactions"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Queued pool transactions"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Blob pool transactions"
    }
   ]
  },
  {
   "title": "Subpool sizes in bytes",
   "type": "timeseries",
   "description": "Tracks a heuristic of the memory footprint of the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool size"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Pending pool size"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Queued pool size"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Blob pool size"
    }
   ]
  },
  {
   "title": "Pending pool imports",
   "type": "timeseries",
   "description": "Number of transactions about to be imported into the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "reth_network_pending_pool_imports{instance=~\"$instance\"}",
     "legendFormat": "Transactions pending import"
    }
   ]
  },
  {
   "title": "Inflight Transaction Requests",
   "type": "timeseries",
   "description": "Currently active outgoing GetPooledTransactions requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "reth_network_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Inflight Transaction Requests"
    }
   ]
  },
  {
   "title": "Inserted transactions",
   "type": "timeseries",
   "description": "Tracks the number of transactions per second that are inserted and removed from the transaction pool, as well as the number of invalid transactions per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(reth_transaction_pool_inserted_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Inserted transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_removed_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Removed transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_invalid_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid transactions"
    }
   ]
  },
  {
   "title": "Transaction Fetcher Hashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "reth_network_hashes_pending_fetch{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Pending Fetch Cache"
    },
    {
     "expr": "reth_network_hashes_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Inflight Requests"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Blob store",
   "type": "timeseries",
   "description": "Tracks the entries, byte size, failed inserts and file deletes of the blob store",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "reth_transaction_pool_blobstore_entries{instance=~\"$instance\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "reth_transaction_pool_blobstore_byte_size{instance=~\"$instance\"}",
     "legendFormat": "Bytesize"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_inserts{instance=~\"$instance\"}",
     "legendFormat": "Failed Inserts"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_deletes{instance=~\"$instance\"}",
     "legendFormat": "Failed Deletes"
    }
   ]
  },
  {
   "title": "Network transaction channel",
   "type": "timeseries",
   "description": "Tracks the number of transaction messages in the channel from the network to the transaction pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(reth_network_pool_transactions_messages_sent{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(reth_network_pool_transactions_messages_received{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "reth_network_pool_transactions_messages_sent{instance=~\"$instance\"} - reth_network_pool_transactions_messages_received{instance=~\"$instance\"}",
     "legendFormat": "Messages in channel"
    }
   ]
  },
  {
   "title": "Transactions Manager Future Poll Duration",
   "type": "timeseries",
   "description": "Duration spent insdie one call to poll the `TransactionsManager` future",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_tx_manager{instance=\"$instance\"}",
     "legendFormat": "Transactions Manager Future"
    }
   ]
  },
  {
   "title": "Transactions Manager Poll Duration Nested Function Calls",
   "type": "timeseries",
   "description": "Accumulated durations of nested function calls, in one call to poll `TransactionsManager` future (`TransactionsManager` future has a loop, hence accumulated).\n\nNetwork Events - stream peer session updates from `NetworkManager`\nTransaction Events - stream txns gossip fom `NetworkManager`\nImported Transactions - stream hashes of successfully inserted txns from `TransactionPool`\nPending pool imports - flush txns to pool from `TransactionsManager`\nFetch Events - stream fetch txn events (success case wraps a tx) from `TransactionFetcher`\nCommands - stream commands from (?) to fetch/serve/propagate txns\n  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_acc_duration_poll_network_events{instance=\"$instance\"}",
     "legendFormat": "Network Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_transaction_events{instance=\"$instance\"}",
     "legendFormat": "Transaction Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_imported_transactions{instance=\"$instance\"}",
     "legendFormat": "Imported Transactions"
    },
    {
     "expr": "reth_network_acc_duration_poll_pending_pool_imports{instance=\"$instance\"}",
     "legendFormat": "Pending Pool Imports"
    },
    {
     "expr": "reth_network_acc_duration_poll_fetch_events{instance=\"$instance\"}",
     "legendFormat": "Fetch Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_commands{instance=\"$instance\"}",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Network Manager Future Poll Duration",
   "type": "timeseries",
   "description": "Duration spent inside one call to poll the `NetworkManager` future",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_network_manager{instance=\"$instance\"}",
     "legendFormat": "Network Manager Future"
    }
   ]
  },
  {
   "title": "Network Manager Poll Duration Nested Function Calls",
   "type": "timeseries",
   "description": "Durations of nested function calls, in one call to poll `NetworkManager` future.\n\nNetwork Handle Message - stream network handle messages from `Transactions`\nSwarm Events - stream txns gossip fom `NetworkManager`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_network_handle{instance=\"$instance\"}",
     "legendFormat": "Network Handle Messages"
    },
    {
     "expr": "reth_network_duration_poll_swarm{instance=\"$instance\"}",
     "legendFormat": "Swarm Events"
    }
   ]
  },
  { "title": "Blockchain Tree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 }, "repeat": "instance" },
  {
   "title": "Canonical chain height",
   "type": "timeseries",
   "description": "The block number of the tip of the canonical chain from the blockchain tree.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height{instance=~\"$instance\"}",
     "legendFormat": "Canonical chain height"
    }
   ]
  },
  {
   "title": "Block buffer blocks",
   "type": "timeseries",
   "description": "Total number of blocks in the tree's block buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_block_buffer_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Sidechains",
   "type": "timeseries",
   "description": "Total number of sidechains in the blockchain tree",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_sidechains{instance=~\"$instance\"}",
     "legendFormat": "Total number of sidechains"
    }
   ]
  },
  {
   "title": "Canonical Commit Latency time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_consensus_engine_beacon_make_canonical_committed_latency_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_consensus_engine_beacon_make_canonical_committed_latency_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Canonicalization duration per action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{instance=~\"$instance\", action=~\"$blockchain_tree_action\", quantile=\"0.5\"} ",
     "legendFormat": "${blockchain_tree_action} {{quantile}} percentile"
    },
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{instance=~\"$instance\", action=~\"$blockchain_tree_action\", quantile=\"0.95\"} ",
     "legendFormat": "${blockchain_tree_action} {{quantile}} percentile"
    },
    {
     "expr": "reth_blockchain_tree_make_canonical_duration{instance=~\"$instance\", action=~\"$blockchain_tree_action\", quantile=\"1\"} ",
     "legendFormat": "${blockchain_tree_action} {{quantile}} percentile"
    }
   ]
  },
  {
   "title": "Latest Reorg Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_latest_reorg_depth{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Engine API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 236 }, "repeat": "instance" },
  {
   "title": "Active block downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_active_block_downloads{instance=~\"$instance\"}",
     "legendFormat": "Active block downloads"
    }
   ]
  },
  {
   "title": "Engine API messages",
   "type": "timeseries",
   "description": "Engine API messages received by the CL, either engine_newPayload or engine_forkchoiceUpdated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_forkchoice_updated_messages{instance=~\"$instance\"}",
     "legendFormat": "Forkchoice updated messages"
    },
    {
     "expr": "reth_consensus_engine_beacon_new_payload_messages{instance=~\"$instance\"}",
     "legendFormat": "New payload messages"
    }
   ]
  },
  {
   "title": "Pipeline runs",
   "type": "timeseries",
   "description": "Total pipeline runs triggered by the sync controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_pipeline_runs{instance=~\"$instance\"}",
     "legendFormat": "Pipeline runs"
    }
   ]
  },
  {
   "title": "Engine API newPayload Latency",
   "type": "timeseries",
   "description": "Latency histogram for the engine_newPayload RPC API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV1 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV1 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV1 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV1 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV1 p99"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV2 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV2 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV2 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV2 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV2 p99"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV3 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV3 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV3 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV3 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV3 p99"
    }
   ]
  },
  {
   "title": "Engine API forkchoiceUpdated Latency",
   "type": "timeseries",
   "description": "Latency histogram for the engine_forkchoiceUpdated RPC API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p99"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p99"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p99"
    }
   ]
  },
  {
   "title": "Engine API getPayloadBodies Latency",
   "type": "timeseries",
   "description": "Latency histograms for the engine_getPayloadBodiesByHashV1 and engine_getPayloadBodiesByRangeV1 RPC APIs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 min"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p50"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p90"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p95"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p99"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 min"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p50"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p90"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p95"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p99"
    }
   ]
  },
  { "title": "Payload Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 }, "repeat": "instance" },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "description": "Number of active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
   "targets": [
    {
     "expr": "reth_payloads_active_jobs{instance=~\"$instance\"}",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Initiated Jobs",
   "type": "timeseries",
   "description": "Total number of initiated jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
   "targets": [
    {
     "expr": "reth_payloads_initiated_jobs{instance=~\"$instance\"}",
     "legendFormat": "Initiated Jobs"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "description": "Total number of failed jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "targets": [
    {
     "expr": "reth_payloads_failed_jobs{instance=~\"$instance\"}",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 278 } },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_jemalloc_active{instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "reth_jemalloc_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "reth_jemalloc_mapped{instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "reth_jemalloc_metadata{instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "reth_jemalloc_resident{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "reth_jemalloc_retained{instance=~\"$instance\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(reth_process_cpu_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "Pruning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 295 } },
  {
   "title": "Pruner duration, total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pruner duration, per segment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_segments_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_segments_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  { "title": "RPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 304 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(reth_rpc_server_connections_connections_opened{instance=~\"$instance\"} - reth_rpc_server_connections_connections_closed{instance=~\"$instance\"}) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Request Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_rpc_server_connections_request_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum call latency per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_rpc_server_calls_time_seconds[$__rate_interval])) by (method) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 313 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_rpc_server_calls_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "RPC Cache Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
   "targets": [
    {
     "expr": "reth_rpc_eth_cache_cached_count{cache=\"evm_env\"}",
     "legendFormat": "EVM environment cache cached items"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{cache=\"receipts\"}",
     "legendFormat": "Receipts cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{cache=\"evm_env\"}",
     "legendFormat": "EVM environment cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{cache=\"blocks\"}",
     "legendFormat": "Block cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_cached_count{cache=\"blocks\"}",
     "legendFormat": "Block cache cached items"
    },
    {
     "expr": "reth_rpc_eth_cache_cached_count{cache=\"receipts\"}",
     "legendFormat": "Receipts cache cached items"
    }
   ]
  }
 ]
}